### ISSUE TITLE
Custom config Class

### ISSUE THREAD

**Issue by emolinablas** [iwasherefirst2/Laravel-MultiMail#12]
I realized that you don't specify that we need to add 'config_class' => true, in multimail.php, I had a hard time understanding why my class wasn't loaded.  Thanks!

**Comment by niels-numbers** [comment]
Why do you think you have to add ` 'config_class' => true` in multimail.php? Never seen that.

**Comment by ccsalazard** [comment]
Dear emolinablas,
Were you able to solve the problem of loading the emails from the database? Will you have an example of how the code goes in the created class and in the multimail.php, please.
