### ISSUE TITLE
How to input just mail provider using class MultiMail

### ISSUE THREAD

**Issue by macerd** [iwasherefirst2/Laravel-MultiMail#19]
I am testing the package and I would like to know if I can only pass through the provider in some way and pass the email address in the mail assembly within the same class. For example:

`
MultiMail::to(...)
                ->providerMail('mailgun')
                ->send(new ConfirmPayment(...));
`

**Comment by niels-numbers** [comment]
You can specify one mail provider for each email as described in the docs, but you can't do that on the fly.  And this package comes only with SMPT  and LOG driver. If you want to use mailgun, you would need to add such a method to https://github.com/iwasherefirst2/laravel-multimail/blob/master/src/TransportManager.php
