### ISSUE TITLE
providers not being detected

### ISSUE THREAD

**Issue by antojqp** [iwasherefirst2/Laravel-MultiMail#2]
Halo! sorry I was going to ask you about one of your repositories on github because it is super suuuuper useful but I found a little error that you had on the MultiMail.php file where when you have a different provider does not pass the correct array and therefore you cannot use it I was wondering if you could open a pull request so I can send u the changes that I did, or if I'm mistaken please tell me how to propertly configure the package it is way too good and is something that actually saved me at work so I want to help 
just in case the error was on the $provider variable where at first was 

```php
[$provider = (!empty($config['provider'])) ? $config['provider'] : config('multimail.provider.default'); ] 
```
so the $provider will only return the name of the provider and not the config array (checked with a dd function and I could only see the provider's name) and I changed it for 

```
[ $provider = (!empty($config['provider'])) ? config('multimail.provider.'.$config['provider']) : config('multimail.provider.default');] 
```

where it takes the name of the provider adn puts it so it can take the configuration, Sorry for the inconvenience and Good Day! you are really amazing and I just want to help

**Comment by niels-numbers** [comment]
Hi antojqp, thank you for your issue. Your right, there is a problem with the service provider. I am going to fix it and create a new release.
