### ISSUE TITLE
Get Mail From Database

### ISSUE THREAD

**Issue by ccsalazard** [iwasherefirst2/Laravel-MultiMail#21]
Dear iwasherefirst2
You could add a more detailed example of how to add the emails from the database. I have followed the documentation steps but I have not been able to. Please help.

**Comment by niels-numbers** [comment]
Hi, yes I have now added default migration files and a default databaseconfig, its explained in https://github.com/iwasherefirst2/laravel-multimail#get-mail-from-database in release 1.3.2

Please let me know if you have any questions about it
