### ISSUE TITLE
Failed to send email with related configuration

### ISSUE THREAD

**Issue by behnamshateri** [iwasherefirst2/Laravel-MultiMail#22]
Im using laravel 7.24 and php 7.4. im try to use this package in order to able to send email to our customer by different mail.
my multiple config is here (i dont dont want save this configuration in database)
```
'emails'  => [
        "test@test.com" => [
            'username'              => "test@test.com",
            'pass'                  => "13455",
        ],
        "test1@test.com" => [
            'username'              => "test1@test.com",
            'pass'                  => "12345",
        ],
    ],
```
if i keep the default email configuration in my env file and then try to send email with multimail i get this errror:
```
vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php - Line:457Expected response code 250 but got code "554", with message "554 5.7.8 User [test@test.com] not authorized to send on behalf of <test1@test.com>
```

if i remove this configuration, i get this error:
```
vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php - Line:457Expected response code 250 but got code "550", with message "550 5.7.1 Relaying denied
```

i have to say that both my email address with related configuration is currect and i test it by default mail facade of Laravel.

whats is the problem with that?

**Comment by niels-numbers** [comment]
Reading the error it seems that your credentials do not match:

```
User [test@test.com] not authorized to send on behalf of <test1@test.com>
```

It probably makes sense that the user `test@test.com` cannot send as `test1@test.com` ?

If username and email are identical, its not necessary to specify username. Try

```
'emails'  => [
        "test@test.com" => [
            'pass'                  => "13455",
        ],
        "test1@test.com" => [
            'pass'                  => "12345",
        ],
],
``` 
does this work?

**Comment by behnamshateri** [comment]
Unfortunately i have to say no.
Is there any open source project that i see it?
is there any need to keep Laravel initial email information in .env file?

**Comment by niels-numbers** [comment]
Yes initial email information is still required in your env

```
MAIL_DRIVER
MAIL_HOST
MAIL_PORT
MAIL_ENCRYPTION
```

should be specified in your .env, because they are used in the default provider from https://github.com/iwasherefirst2/laravel-multimail/blob/master/publishable/config/multimail.php

Do you have these 4 options in your `.env` ? Can you post you full `config/multimail.php` ?

The error that you shown is pretty clearly a configuration error.

**Comment by niels-numbers** [comment]
Any updates here?

**Comment by niels-numbers** [comment]
Close it as it seems to be resolved. If you still have a problem, I will reopen it.
