### ISSUE TITLE
Support Reply To Option

### ISSUE THREAD

**Issue by teverestek** [iwasherefirst2/Laravel-MultiMail#23]
Hi, 
Thanks for the great plugin.
Can we use replyTo option while sending email. As i need a dynamic replyTo for receiving emails if any user click on replyTo button?

**Comment by niels-numbers** [comment]
Hi, yes, thats default functionality from Laravel.  You may set this in the build function of your mailable class, something like this:

    public function build()
    {
        return $this->replyTo('email', $name = 'name')
                 ->markdown('emails.invitation');
    }

**Comment by teverestek** [comment]
Hi Adam,

Thanks for the update.
Appreciate it.


Thanks & Regards,
*Tejas Patel*
*Senior Software Engineer*
M-9769985020
*Everestek Technosoft Solutions Pvt Ltd. <http://www.everestek.com/>*
