### ISSUE TITLE
from_name dynamic

### ISSUE THREAD

**Issue by ecano08** [iwasherefirst2/Laravel-MultiMail#24]
Hello, I want to know Is possible to pass a variable in order to use the from_name? 
Thanks

**Comment by niels-numbers** [comment]
Good point, thats actually not possible currently. I will add an option to pass it as 2nd parameter to `from` just as it works for default mail. Not sure when I have time to do this, but I add it on my list.

**Comment by niels-numbers** [comment]
You can now pass a dynamical from name using the package as `Multimail::from($key, $dynamicFromName)`. Please make sure to update to version 1.3.4

**Comment by ecano08** [comment]
> You can now pass a dynamical from name using the package as `Multimail::from($key, $dynamicFromName)`. Please make sure to update to version 1.3.4

Excellent, thank you!
