### ISSUE TITLE
Log driver throw error if pass or username missed

### ISSUE THREAD

**Issue by arturmamedov** [iwasherefirst2/Laravel-MultiMail#5]
This commit say that is not longer required c3926ca4efda501f421b6f5145130ec74c64aa19
But i still receive error on log driver when pass or username are missing

```
Username or password for log is missing in config/multimail.php and no default specified!
```

Maybe i make wrong config

```
'emails' => [
// ...
'log' => [
    'from_mail' => 'info@...',
    'from_name' => "... CMS",

    'provider' => 'log'
],
// ...
'provider' => [
// ...
'log' => [
    'driver' => 'log',
],
```

**Comment by niels-numbers** [comment]
Oh thats strange. It seems to work if you use the email directly: 

```
'emails' => [
// ...
'info@xyz.com' => [
    'from_name' => "... CMS",

    'provider' => 'log'
],
// ...
'provider' => [
// ...
'log' => [
    'driver' => 'log',
],
```
I will try to fix the bug.

**Comment by niels-numbers** [comment]
So its actually designed to use the email as key in `emails` array. This was not the case in the initial config. I updated it, so its now in sync with the docs and everything should work :)
