### ISSUE TITLE
Add a custom channel in the package to be able to use in Notifiables

### ISSUE THREAD

**Issue by Tofandel** [iwasherefirst2/Laravel-MultiMail#7]
See https://laravel.com/docs/7.x/notifications#custom-channels
This will allow for notifiables to be sent via the channel

The class should also correctly implement `\Illuminate\Contracts\Mail\Mailer` currently it doesn't and the send method is incompatible

The methods of the facade should also be added as DocComments for correct typing and IDE autocompletion

**Comment by niels-numbers** [comment]
> See https://laravel.com/docs/7.x/notifications#custom-channels
> This will allow for notifiables to be sent via the channel

How would you determine to which emailadresses the notification should be send? I feel like it may be best to leave it to the enduser to create his own Notification Channel and use `MultiMail` inside?

> The class should also correctly implement `\Illuminate\Contracts\Mail\Mailer` currently it doesn't and the send method is incompatible

What would be the benefit if MultiMail implements `\Illuminate\Contracts\Mail\Mailer` ?
> 
> The methods of the facade should also be added as DocComments for correct typing and IDE autocompletion

You mean `    protected static function getFacadeAccessor()` ? I add that.

**Comment by niels-numbers** [comment]
Feel free to send a merge request if you want that implementet
