### ISSUE TITLE
Issue when provider is Sparkpost

### ISSUE THREAD

**Issue by eichgi** [iwasherefirst2/Laravel-MultiMail#8]
I created a provider as follows:

````
'provider' => [
        'sparkpost' => [
            'host' => 'smtp.sparkpostmail.com',
            'port' => 587,
            'encryption' => env('MAIL_ENCRYPTION'),
            'driver' => 'smtp',
        ]
````
as well as an email for that provider:

````
'no-reply@domain.xyz' => [
            'username' => 'no-reply@domain.xyz',
            'pass' => env('SPARKPOST_SECRET'),
            'from_name' => 'My name',
            'provider' => 'sparkpost',
        ]
````

But I get: 
Failed to authenticate on SMTP server with username "no-reply@domain.xyz" using 2 possible authenticators. Authenticator LOGIN returned Swift_TransportException: Expected response code 235 but got code "535", with message "535 5.7.8 Authentication credentials invalid.

When using the default Mail facade with sparkpost all emails are sent, which lead me to think that "pass" key in the defined email is not being set up correctly. 

Could you help me out to sort this?

**Comment by niels-numbers** [comment]
Did you got it fixed? Error 535 could mean that your login credentials are not working - try for a test to put them directly in your config.php, maybe your `env` is not working? Also it could be related to you mail settings.

https://www.nativespace.com/mynative/knowledgebase/61/Error-535---Incorrect-authentication-data.html
https://stackoverflow.com/questions/3547388/php-swift-mailer-failed-to-authenticate-on-smtp-using-2-possible-authenticators
https://laracasts.com/discuss/channels/laravel/failed-to-authenticate-on-smtp-server-with-username-my-at-emailcom-using-2-possible-authenticators
