### ISSUE TITLE
How to load the email configuration from a database?

### ISSUE THREAD

**Issue by Jedliu** [iwasherefirst2/Laravel-MultiMail#9]
Hi there,

How to load the email clients and providers from a database other than from the config file?

Thank you,

**Comment by niels-numbers** [comment]
Currently its not possible but it would be if would would resolve the config class from the service container (and bind it to the service container also) https://github.com/iwasherefirst2/laravel-multimail/blob/18cea7023a47d9560b82fcf53cb20e5f879abd68/src/MultiMailer.php#L39

Feel free to send a MR for that.

The you would need to overwrite the ServcieProvider as explained here https://stackoverflow.com/a/50220159/2311074 and replace it with your own config class, which reads the credentials from your DB

**Comment by Jedliu** [comment]
Thank you for your prompt reply! I will fork it and test first.

**Comment by niels-numbers** [comment]
@Jedliu note the Config class would need a custom `initialise` method instead of the constructor, because we need to 1) resolve the config class and 2) then pass the `$key`.

**Comment by Jedliu** [comment]
Would you please check this and let me know your comments? 
[https://github.com/iwasherefirst2/laravel-multimail/compare/master...Jedliu:master](Compare)

I did the following:
1, modify the config constructor
2, add one more exception
3, add function to validate the email setting

I will just call it like `MultiMail::from($setting)->send(new DefaultMail());` and pass the $setting as an array instead of the email address.

Thank you,

**Comment by niels-numbers** [comment]
@Jedliu so I a look into https://github.com/iwasherefirst2/laravel-multimail/compare/master...Jedliu:master

First, thanks for your help. Regarding your code:

1) Your validation returns either a string or a message, I think that is inconstant. Also you don't seem to use it?
2) I don't like to add more logic to the constructor at https://github.com/Jedliu/laravel-multimail/blob/7b938f5f892c8a1be8a2a66494ce157888fabc1d/src/Config.php#L44-L54 instead I would like to use SOLID principles here.

Instead, I made the config class now be resolvable . If you want to load your email configs from database or whatever, please do so as instructed in https://github.com/iwasherefirst2/laravel-multimail#get-mail-from-database 

Note that you require version 1.3.1
